window.QUESTION_BANK = [
  {
    "id": 1,
    "topic": "The Four Operations of Whole Numbers",
    "question": "Peter answered 15 quiz questions for 29 points. A correct answer earns 3 points and a wrong answer loses 1 point. How many were correct?",
    "answer": "11 questions",
    "model": "unit-bar",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 5,
    "questionZh": "彼得答了15道测验题，共得29分。答对1题得3分，答错1题扣1分。彼得答对了多少题？",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 2,
    "topic": "The Four Operations of Whole Numbers",
    "question": "A box had 480 yellow, orange, and black beads. After 18 yellow beads were added, 33 orange beads were removed, and black beads were doubled, the 3 colours were equal. Find each original count.",
    "answer": "Yellow: 168; orange: 219; black: 93",
    "model": "unit-bar",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 5,
    "questionZh": "一个盒子里有480颗黄色、橙色和黑色珠子。加入18颗黄色珠子、取走33颗橙色珠子，并把黑色珠子的数量增加到原来的2倍后，3种颜色的珠子数量相等。求每种珠子原来的数量。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 3,
    "topic": "The Four Operations of Whole Numbers",
    "question": "40% of Angie’s beads were red. After she lost 50 blue beads, blue beads were 1/2 of their original count. How many beads did Angie have in the end?",
    "answer": "200 beads",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 5,
    "questionZh": "安琪的珠子中有40%是红色的。她丢失50颗蓝色珠子后，蓝色珠子的数量变为原来的1/2。安琪最后有多少颗珠子？",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 4,
    "topic": "The Four Operations of Whole Numbers",
    "question": "There were 820 orange buttons, 160 fewer than yellow and 210 more than green. Blue buttons were 1/4 of the total. How many buttons were there altogether?",
    "answer": "3615 buttons",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 6,
    "questionZh": "有820颗橙色纽扣，比黄色纽扣少160颗，比绿色纽扣多210颗。蓝色纽扣占总数的1/4。纽扣一共有多少颗？",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 5,
    "topic": "The Four Operations of Whole Numbers",
    "question": "Benjamin sold apples and oranges. He sold 2 more apples; oranges cost $3, apples $2, and he received $1 for every 10 fruit. The sale total after payment was $62. Find each count.",
    "answer": "12 oranges; 14 apples",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 6,
    "questionZh": "本杰明卖苹果和橙子。他卖的苹果比橙子多2个；橙子每个$3，苹果每个$2，并且每卖出10个水果可获得$1。收款后总销售额为$62。求苹果和橙子各卖了多少个。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 6,
    "topic": "The Four Operations of Whole Numbers",
    "question": "160 paperclips were in boxes A, B, C, D. 12 moved A→B, 1/4 of B moved B→C, and 17 moved D→C. All boxes then matched. Find original counts.",
    "answer": "A: 52; B: 48; C: 3; D: 57",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 6,
    "questionZh": "160个回形针放在A、B、C、D 4个盒子里。将12个从A移到B，将B中1/4的回形针移到C，又将17个从D移到C后，所有盒子里的回形针数量相等。求各盒原来的数量。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 7,
    "topic": "The Four Operations of Whole Numbers",
    "question": "Michael had 80% more money than Alvin; Vanessa had 40% less. Michael and Alvin gave Vanessa money in a 3:2 ratio. Vanessa then had 2 times her original amount; Michael ended $144 above Vanessa. Find original amounts.",
    "answer": "Michael: $1080; Alvin: $600; Vanessa: $360",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 7,
    "questionZh": "迈克尔的钱比阿尔文多80%；瓦妮莎的钱比阿尔文少40%。迈克尔和阿尔文按3:2的比例给瓦妮莎钱。之后瓦妮莎的钱变为原来的2倍；迈克尔最后比瓦妮莎多$144。求三人原来各有多少钱。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 8,
    "topic": "The Four Operations of Whole Numbers",
    "question": "4/9 of Tom’s toy cars were red. Green exceeded red by 35 and yellow cars numbered 15. Packing 5 same-colour cars per box, how many more red-and-green boxes than yellow boxes were there?",
    "answer": "44 boxes",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 7,
    "questionZh": "汤姆的玩具车中有4/9是红色的。绿色玩具车比红色的多35辆，黄色玩具车有15辆。若每盒装5辆同色玩具车，红色和绿色玩具车的盒数合计比黄色玩具车的盒数多多少？",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 9,
    "topic": "The Four Operations of Whole Numbers",
    "question": "David had 1/3 as many cards as Kristy. David gave away 9; Kristy bought 18; their final ratio was 2:9. How many cards did they have altogether in the end?",
    "answer": "99 cards",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 7,
    "questionZh": "大卫的卡片数量是克里斯蒂的1/3。大卫送出9张卡片，克里斯蒂买了18张卡片后，两人的卡片数量之比为2:9。最后两人一共有多少张卡片？",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 10,
    "topic": "The Four Operations of Whole Numbers",
    "question": "3/4 of 42 students passed English. 1/4 of those who passed were girls, and 4 more boys than girls failed. How many girls were in the class?",
    "answer": "23 girls",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 8,
    "questionZh": "42名学生中有3/4通过了英语考试。通过考试的学生中有1/4是女生；未通过考试的男生比女生多4人。班上有多少名女生？",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 11,
    "topic": "The Four Operations of Whole Numbers",
    "question": "Mrs Drew sold 120 butter and chocolate-chip cookies. Butter cost $2, chocolate-chip cost $4, and sales were $310. How many more butter cookies were sold?",
    "answer": "50 more butter cookies",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 8,
    "questionZh": "德鲁太太卖出120块黄油饼干和巧克力碎片饼干。黄油饼干每块$2，巧克力碎片饼干每块$4，总销售额为$310。黄油饼干比巧克力碎片饼干多卖出多少块？",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 12,
    "topic": "The Four Operations of Whole Numbers",
    "question": "Jane and John had 180 marbles. After Jane gave John marbles, John had 3 times his original count and Jane had 1/2 of John’s count. Find original counts.",
    "answer": "Jane: 140; John: 40",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 8,
    "questionZh": "简和约翰共有180颗弹珠。简给约翰一些弹珠后，约翰的弹珠数量变为原来的3倍，简的弹珠数量是约翰的1/2。求两人原来各有多少颗弹珠。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 13,
    "topic": "The Four Operations of Whole Numbers",
    "question": "2/3 of a number exceeds 1/4 of it by 12. Find the difference between the number and its 4th multiple.",
    "answer": "360",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 9,
    "questionZh": "一个数的2/3比它的1/4多12。求这个数与它的4倍之间的差。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 14,
    "topic": "The Four Operations of Whole Numbers",
    "question": "105 students were in 3 groups. 1/4 of group 1 and 20% of group 3 moved to group 2; 15 then moved group 1→3. All groups then matched. Find original counts.",
    "answer": "Group 1: 75; Group 2: 5; Group 3: 25",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 9,
    "questionZh": "105名学生分成3组。第1组的1/4和第3组的20%调到第2组；随后又有15名学生从第1组调到第3组。此时3组人数相等。求各组原来的人数。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 15,
    "topic": "The Four Operations of Whole Numbers",
    "question": "In 1998, Tom was 4 times Jack’s age and Peter was 2 times Jack’s age. Tom was 36. Find Peter’s age in 2000 and their total age in 2003.",
    "answer": "(a) 20 years; (b) 78 years",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 9,
    "questionZh": "1998年，汤姆的年龄是杰克的4倍，彼得的年龄是杰克的2倍。汤姆当时36岁。求彼得在2000年的年龄，以及3人在2003年的年龄总和。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 16,
    "topic": "The Four Operations of Whole Numbers",
    "question": "Thomas and Zack each received equal toy-car amounts. Zack then had 2 times his original count; 3/4 of Zack’s count equalled 1/2 of Thomas’s count, and Thomas was 36 ahead. Find both requested values.",
    "answer": "(a) 108 cars; (b) 90 cars",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 10,
    "questionZh": "托马斯和扎克各自收到同样数量的玩具车。之后扎克的玩具车数量变为原来的2倍；扎克数量的3/4等于托马斯数量的1/2，并且托马斯比扎克多36辆。求题目所要求的两个数值。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 17,
    "topic": "The Four Operations of Whole Numbers",
    "question": "Joanne sold cookies, cakes, muffins. Cookies exceeded cakes by 140; 1/2 of cookies and 1/3 of cakes were chocolate. Use the stated equal flavour relationships to find the requested difference and sales total.",
    "answer": "(a) 60 more; (b) $350",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 10,
    "questionZh": "乔安妮卖饼干、蛋糕和松饼。饼干比蛋糕多140个；饼干的1/2和蛋糕的1/3是巧克力味的。利用题目给出的口味数量相等关系，求所要求的数量差和销售总额。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 18,
    "topic": "The Four Operations of Whole Numbers",
    "question": "4656 people attended a concert. After 1/4 of men and 1/3 of women left, 120 more women remained. How many more women than men were there at first?",
    "answer": "16 more women",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 10,
    "questionZh": "4656人参加了一场音乐会。1/4的男士和1/3的女士离开后，留下的女士比男士多120人。起初女士比男士多多少人？",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 19,
    "topic": "The Four Operations of Whole Numbers",
    "question": "1/3 of 120 oranges were ripe and the rest overripe. After 40 were removed, overripe oranges were 3/4 of the remainder. Find removed ripe, removed overripe, and final difference.",
    "answer": "(a) 20 overripe; (b) 20 ripe; (c) 40 more overripe",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 11,
    "questionZh": "120个橙子中有1/3成熟，其余过熟。取走40个橙子后，过熟橙子占剩余橙子的3/4。求取走的成熟橙子数、取走的过熟橙子数，以及最后两者数量之差。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 20,
    "topic": "Measurement",
    "question": "Mrs Crawford spent 1/3 of salary on education and 1/4 of the remainder on food. Savings:transport was 2:3; education exceeded transport by $265. Find 6 months of education spending.",
    "answer": "$3975",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 11,
    "questionZh": "克劳福德太太将工资的1/3用于教育，又将余下部分的1/4用于食物。储蓄与交通费之比为2:3；教育支出比交通费多$265。求6个月的教育支出。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 21,
    "topic": "Measurement",
    "question": "Tank A was 2/3 full. 1/2 of its water filled tank B from 1/4 full to full. Tank A measured 12 cm × 10 cm × 20 cm. Find total tank capacity in litres.",
    "answer": "3.4 L",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 11,
    "questionZh": "水箱A装有2/3满的水。其中1/2的水把原本装有1/4水的水箱B加满。水箱A的尺寸为12 cm × 10 cm × 20 cm。求两个水箱的总容量（以升为单位）。",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 22,
    "topic": "Measurement",
    "question": "Mrs Bowles bought 2.5 kg fish and 1.5 kg more prawns. Change from $50 was $5.50; prawns cost $3/kg more. How much did she spend on prawns?",
    "answer": "$32",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 12,
    "questionZh": "鲍尔斯太太买了2.5 kg鱼和比鱼多1.5 kg的虾。从$50找回$5.50；虾每kg比鱼贵$3。她买虾花了多少钱？",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 23,
    "topic": "Measurement",
    "question": "A 60 cm × 40 cm × 25 cm container was 4/5 full; its water level fell 5 cm. Remaining water filled a tank and basin, whose capacity was 1/4 of the tank. Find tank water height.",
    "answer": "100 cm",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 12,
    "questionZh": "一个60 cm × 40 cm × 25 cm的容器装有4/5满的水；水位下降了5 cm。剩下的水装满一个水箱和一个盆，盆的容量是水箱容量的1/4。求水箱中的水高。",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 24,
    "topic": "Measurement",
    "question": "ABCD is a 320 cm-perimeter rectangle of length 96 cm. 2 squares of side 12 cm are placed inside. Find the shaded area, using π = 3.14.",
    "answer": "6020.16 cm²",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 12,
    "questionZh": "ABCD是一个周长为320 cm、长为96 cm的长方形。里面放有2个边长为12 cm的正方形。取π = 3.14，求阴影部分的面积。",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 25,
    "topic": "Measurement",
    "question": "Joanne bought 3 pens and 2 rulers for $10.80; Alice bought 5 pens and 4 rulers for $19.20. Nick spent $13.20 on 2 rulers and pens. How many pens did Nick buy?",
    "answer": "4 pens",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 13,
    "questionZh": "乔安妮买3支笔和2把尺共花$10.80；爱丽丝买5支笔和4把尺共花$19.20。尼克买2把尺和若干支笔共花$13.20。尼克买了多少支笔？",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 26,
    "topic": "Measurement",
    "question": "Frankie, Martin, and Jeremy earned $120. Jeremy earned 1/2 Frankie; Martin earned 3 times Jeremy and gave Frankie 1/4 of his money. Jeremy then earned 4 times his earlier amount. How much more did Jeremy have?",
    "answer": "$25",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 13,
    "questionZh": "弗兰基、马丁和杰里米共赚了$120。杰里米赚的钱是弗兰基的1/2；马丁赚的钱是杰里米的3倍，并给了弗兰基自己钱的1/4。杰里米之后赚到的钱是先前的4倍。杰里米的钱增加了多少？",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 27,
    "topic": "Measurement",
    "question": "A 90 cm × 10 cm tank was filled by taps at 4 L/min and 10 L per 2 min. After 1.5 min it was 1/4 full. Find tank height.",
    "answer": "60 cm",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 13,
    "questionZh": "一个底面为90 cm × 10 cm的水箱由两个水龙头注水，流量分别为4 L/min和每2 min 10 L。注水1.5 min后，水箱装了1/4满。求水箱的高度。",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 28,
    "topic": "Measurement",
    "question": "PQRS is enlarged to VWRT; area increases 226 cm². PQRS length is 2 times breadth. Find PQRS perimeter.",
    "answer": "105 cm",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 14,
    "questionZh": "PQRS放大为VWRT后，面积增加226 cm²。PQRS的长是宽的2倍。求PQRS的周长。",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 29,
    "topic": "Measurement",
    "question": "Tank A was 30% full. 2/5 of its water filled 1/2 of empty tank B, sized 15 cm × 12 cm × 25 cm. How much water is now needed to fill A?",
    "answer": "15375 cm³",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 14,
    "questionZh": "水箱A原来装有30%满的水。其中2/5的水装满了空水箱B的1/2。水箱B的尺寸为15 cm × 12 cm × 25 cm。现在还需要多少水才能装满A？",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 30,
    "topic": "Measurement",
    "question": "Patrick, Jemima, Angela had $482. Angela had 3/4 of Jemima; after Patrick used $125, he had 1/4 less than Jemima. Find initial Patrick-plus-Angela total.",
    "answer": "$314",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 14,
    "questionZh": "帕特里克、杰米玛和安吉拉共有$482。安吉拉的钱是杰米玛的3/4；帕特里克用了$125后，他的钱比杰米玛少1/4。求帕特里克和安吉拉起初的钱数总和。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 31,
    "topic": "Measurement",
    "question": "Red:yellow beads were 10:9. After 30 yellow beads were used, the ratio was 5:2. Red cost $0.90 each; yellow cost $0.20 more. Find original cost.",
    "answer": "$113.40",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 15,
    "questionZh": "红色珠子与黄色珠子的数量之比为10:9。用掉30颗黄色珠子后，数量之比变为5:2。红色珠子每颗$0.90；黄色珠子每颗贵$0.20。求这些珠子原来的总价。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 32,
    "topic": "Measurement",
    "question": "A semicircle and small triangle lie in triangle PQR; PQ is the semicircle diameter. Using the given 36 cm figure and π = 3.14, find the unshaded area.",
    "answer": "59.48 cm²",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 15,
    "questionZh": "三角形PQR内有一个半圆和一个小三角形；PQ是半圆的直径。根据图中给出的36 cm，取π = 3.14，求非阴影部分的面积。",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 33,
    "topic": "Measurement",
    "question": "A 70 cm × 45 cm × 50 cm tank filled from 2 taps at 7 L/min each for 10 min. 30% was poured into a tub to make it 3/10 full. Find water needed to fill both.",
    "answer": "73500 cm³ or 73.5 L",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 15,
    "questionZh": "一个70 cm × 45 cm × 50 cm的水箱由2个流量均为7 L/min的水龙头注水10 min。将其中30%的水倒入一个浴盆，使浴盆达到3/10满。求将水箱和浴盆都加满还需要多少水。",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 34,
    "topic": "Measurement",
    "question": "Clocks chime every 3 min, 4 min offset by 1 min, and 6 min. They chime together at 10:45 am. How many more joint chimes occur in the next hour?",
    "answer": "5 times",
    "model": "unit-bar",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 16,
    "questionZh": "3个时钟分别每3 min、每4 min（相差1 min）和每6 min报时。它们在上午10:45同时报时。接下来1 h内还会同时报时多少次？",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 35,
    "topic": "Measurement",
    "question": "Frederick and Justina spend $8/$16 per day, leaving Justina $70; swapping spending gives Justina $430. Find their parent-given amounts.",
    "answer": "Frederick: $240; Justina: $550",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 16,
    "questionZh": "弗雷德里克和朱斯蒂娜每天分别花$8和$16，朱斯蒂娜剩下$70；若两人交换每天的花费，朱斯蒂娜会剩下$430。求父母分别给了他们多少钱。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 36,
    "topic": "Measurement",
    "question": "Tank A:B water was 4:3. Adding 0.8 L filled A, making A 2 times B. A capacity was 1/4 of B capacity. How much more water fills B?",
    "answer": "8.4 L",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 16,
    "questionZh": "水箱A与B中的水量之比为4:3。向A加入0.8 L水后，A中的水量变为B中的2倍。A的容量是B容量的1/4。要把B装满，还要加多少水？",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 37,
    "topic": "Measurement",
    "question": "Germaine spent $70 and had 2 times Gilbert. Gilbert received $300 and had 3 times Germaine’s original amount. Find their final total.",
    "answer": "$354",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 17,
    "questionZh": "杰曼花掉$70后，剩下的钱是吉尔伯特的2倍。吉尔伯特得到$300后，钱数是杰曼原有钱数的3倍。求两人最后的钱数总和。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 38,
    "topic": "Measurement",
    "question": "3 books + 2 magazines cost $84; 3 comics + 2 magazines cost $54; 2 comics + 2 books cost $52. Find 1 magazine cost.",
    "answer": "$15",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 17,
    "questionZh": "3本书和2本杂志共$84；3本漫画书和2本杂志共$54；2本漫画书和2本书共$52。求1本杂志的价格。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 39,
    "topic": "Measurement",
    "question": "2 concentric circles have radii 7 cm and 21 cm. Shaded:unshaded area is 2:7. Find unshaded area using π = 22/7.",
    "answer": "4312 cm²",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 17,
    "questionZh": "2个同心圆的半径分别为7 cm和21 cm。阴影部分与非阴影部分的面积之比为2:7。取π = 22/7，求非阴影部分的面积。",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 40,
    "topic": "Measurement",
    "question": "A 12 cm × 15 cm × 30 cm container became 2/3 full; added tub water left 20% of tub’s original volume. Tub base was 24 cm × 15 cm. Find original water level.",
    "answer": "6.25 cm",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 18,
    "questionZh": "一个12 cm × 15 cm × 30 cm的容器装到2/3满；倒入其中的浴盆水后，浴盆剩下原来体积的20%。浴盆底面为24 cm × 15 cm。求浴盆原来的水深。",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 41,
    "topic": "Measurement",
    "question": "6 similar rectangles form figure A and are rearranged to figure B. Figure A area is 864 cm². Find figure B perimeter.",
    "answer": "156 cm",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 18,
    "questionZh": "6个全等长方形组成图形A，重新排列后形成图形B。图形A的面积为864 cm²。求图形B的周长。",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 42,
    "topic": "Measurement",
    "question": "A fruiterer sold 30% more apples than oranges and 10% more pears; 104 apples. Bags and prices were 4/$6, 8/$10, 2/$3. Find total sales.",
    "answer": "$386",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 18,
    "questionZh": "一名水果商卖出的苹果比橙子多30%，比梨多10%；卖出了104个苹果。水果按每袋4个$6、每袋8个$10、每袋2个$3出售。求总销售额。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 43,
    "topic": "Measurement",
    "question": "4 oranges, 3 apples, 2 papayas cost $15.50; 2 oranges, 6 papayas $28.60; 3 oranges, 4 apples $6.80. Find each price.",
    "answer": "Apple: $1.10; Orange: $0.80; Papaya: $4.50",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 19,
    "questionZh": "4个橙子、3个苹果和2个木瓜共$15.50；2个橙子和6个木瓜共$28.60；3个橙子和4个苹果共$6.80。求每种水果的单价。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 44,
    "topic": "Measurement",
    "question": "A tap fills at 3 L/min and a hole drains 0.5 L/min. Starting 7:00 am, find pail water at 9:30 am and time to reach 10 L.",
    "answer": "(a) 375 L; (b) 4 minutes",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 19,
    "questionZh": "一个水龙头以3 L/min注水，一个洞以0.5 L/min漏水。从上午7:00开始，求上午9:30桶中的水量，以及桶中水达到10 L的时间。",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 45,
    "topic": "Measurement",
    "question": "Orange juice was split A/B/C. 20 ml moved B→C, 210 ml C→A, 150 ml removed A. Final A was 3 times initial A; B=C=3 times final A. Find initial amounts and carton total.",
    "answer": "A: 30 ml; B: 290 ml; C: 460 ml; total: 780 ml",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 19,
    "questionZh": "橙汁分装在A、B、C 3个容器中。将20 ml从B移到C，将210 ml从C移到A，再从A取走150 ml。最后A中的橙汁是原来A中的3倍；B和C中的橙汁都等于最后A中的3倍。求各容器原来的橙汁量和纸盒中的橙汁总量。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 46,
    "topic": "Measurement",
    "question": "Joanne gave 1/3 to her mother then saved:spent 1:2. Alex spent 1/4 clothes and 1/4 books; Joanne’s gift equalled Alex’s books. Her $180 transfer leaves 1/4 of Alex’s savings. Find requested values.",
    "answer": "(a) Joanne: $1440; Alex: $1080; (b) $1260",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 20,
    "questionZh": "乔安妮先把钱的1/3给母亲，之后储蓄与花费之比为1:2。亚历克斯把钱的1/4花在衣服上，1/4花在书上；乔安妮给母亲的钱等于亚历克斯买书的钱。乔安妮转给亚历克斯$180后，所转的钱是亚历克斯储蓄的1/4。求题目所要求的数值。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 47,
    "topic": "Measurement",
    "question": "2 taps add 6 L/min each while a hole drains 8 L per 4 min. A tank is 40% full after 10 min. Find capacity and extra fill time.",
    "answer": "(a) 250 L; (b) 15 minutes",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 20,
    "questionZh": "2个水龙头各以6 L/min注水，同时一个洞每4 min漏8 L水。10 min后水箱装了40%满。求水箱容量，以及再过多久能装满。",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 48,
    "topic": "Measurement",
    "question": "Mary had $50, Tom $130. Their mother gave equal daily amounts; after 2 days Mary had 2 times Tom. Find total given and Mary’s daily amount.",
    "answer": "(a) $220; (b) $55",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 20,
    "questionZh": "玛丽有$50，汤姆有$130。他们的母亲每天给两人相同的钱；2天后玛丽的钱是汤姆的2倍。求母亲一共给了多少钱，以及玛丽每天得到多少钱。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 49,
    "topic": "Measurement",
    "question": "Square perimeters A:B were 3:5, shaded-rectangle perimeter:A was 2:6, and square perimeters totalled 192 cm. Find 3 requested areas.",
    "answer": "(a) 27 cm²; (b) 873 cm²; (c) 1170 cm²",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 21,
    "questionZh": "正方形A与B的周长之比为3:5，阴影长方形的周长与A的周长之比为2:6，两个正方形的周长总和为192 cm。求3个所要求的面积。",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 50,
    "topic": "Measurement",
    "question": "A rectangle contains 2 quadrants of radii 12 cm and 24 cm. Find the difference in shaded areas using π = 3.14.",
    "answer": "51.12 cm²",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 21,
    "questionZh": "一个长方形内有2个半径分别为12 cm和24 cm的四分之一圆。取π = 3.14，求阴影部分面积之差。",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 51,
    "topic": "Fractions",
    "question": "Basins A, B, C are identical. A has mass 3.1 kg at 1/4 full and B 2.2 kg at 3/4 full. Find C’s filled fraction when it has mass 2.8 kg.",
    "answer": "5/7",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 21,
    "questionZh": "A、B、C是相同的盆。A装1/4满时质量为3.1 kg，B装3/4满时质量为2.2 kg。C的质量为2.8 kg时，装了几分之几满？",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 52,
    "topic": "Fractions",
    "question": "A 20 cm × 12 cm × 15 cm tank had water. After 1/10 was poured into a tub, tub volume increased 12 cm³. What fraction of tank capacity was unfilled at first?",
    "answer": "29/30",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 22,
    "questionZh": "一个20 cm × 12 cm × 15 cm的水箱中有水。倒出其中的1/10到一个盆里后，盆里的水量增加12 cm³。起初水箱未装满的部分占水箱容量的几分之几？",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 53,
    "topic": "Fractions",
    "question": "Mathew sold 1/3 of pens on day 1, 4 more on day 2, then the rest day 3. Day 2 exceeded day 3 by 15. Find original pens.",
    "answer": "36 pens",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 22,
    "questionZh": "马修第1天卖出笔的1/3，第2天再卖出4支，其余在第3天卖出。第2天比第3天多卖15支笔。求原来有多少支笔。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 54,
    "topic": "Fractions",
    "question": "Edmund bought small $4, medium $6, large $8 cookie packs. 1/4 were small, medium exceeded small by 4, total was $180. Find each pack count.",
    "answer": "Small: 15; Medium: 16; Large: 3",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 22,
    "questionZh": "埃德蒙买了小、中、大3种装的饼干，价格分别为$4、$6、$8。小包装占总数的1/4；中包装比小包装多4包，总价为$180。求各种包装各买了多少包。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 55,
    "topic": "Fractions",
    "question": "Ben and Tom had 144 sweets. Ben gave Tom 1/4 of his; Tom gave Ben 1/3 of his; they then matched. Find original counts.",
    "answer": "Ben: 60; Tom: 84",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 23,
    "questionZh": "本和汤姆共有144颗糖。本给汤姆自己糖的1/4；汤姆给本自己糖的1/3后，两人的糖数相等。求两人原来各有多少颗糖。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 56,
    "topic": "Fractions",
    "question": "Claudia gave Agnes 1/4 of her curry puffs; Agnes gave Claudia 1/3 of hers. They then matched and had 240 total. Find original counts.",
    "answer": "Claudia: 144; Agnes: 96",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 23,
    "questionZh": "克劳迪娅给阿格尼丝自己咖喱角的1/4；阿格尼丝给克劳迪娅自己咖喱角的1/3后，两人的数量相等，共有240个。求两人原来各有多少个。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 57,
    "topic": "Fractions",
    "question": "A florist sold 1/5 of orchids and 1/3 of roses, leaving 60. After 14 more roses sold, 1/2 of original roses remained. Find original fruit total.",
    "answer": "80 orchids and roses",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 23,
    "questionZh": "一名花商卖出兰花的1/5和玫瑰的1/3后，剩下60朵。又卖出14朵玫瑰后，剩下的玫瑰是原来数量的1/2。求原来花的总数。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 58,
    "topic": "Fractions",
    "question": "Of Chinese, English, Malay books, 1/4 were Chinese and 1/3 of the remainder English. Malay exceeded English by 63. Find each count.",
    "answer": "Chinese: 35; English: 21; Malay: 84",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 24,
    "questionZh": "中文书、英文书和马来文书中，中文书占1/4；余下的书中有1/3是英文书。马来文书比英文书多63本。求每种书各有多少本。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 59,
    "topic": "Fractions",
    "question": "After selling 1/3 of apples and 7 pears, pears left were 1/4 apples left. Pears sold were 1/7 pears not sold. Find original fruit counts.",
    "answer": "Apples: 252; Pears: 49",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 24,
    "questionZh": "卖出苹果的1/3和7个梨后，剩下的梨是剩下苹果的1/4。卖出的梨是未卖出梨的1/7。求原来苹果和梨各有多少个。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 60,
    "topic": "Fractions",
    "question": "1/4 of Mr Jones’s notes were $2; 2/3 of the rest were $10; remaining were $5. Total was $295. How many $10 notes?",
    "answer": "15 ten-dollar notes",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 24,
    "questionZh": "琼斯先生的纸币中有1/4是$2纸币；其余纸币中有2/3是$10纸币，剩下的是$5纸币。总额为$295。有多少张$10纸币？",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 61,
    "topic": "Fractions",
    "question": "Jim and Alice had marbles. 1/4 of Jim’s count was 1/3 of Alice’s. Jim gave Alice 30; Alice was then 40 ahead; Jim had 2/3 left. Find original counts.",
    "answer": "Jim: 80; Alice: 60",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 25,
    "questionZh": "吉姆和爱丽丝有一些弹珠。吉姆弹珠数的1/4等于爱丽丝弹珠数的1/3。吉姆给爱丽丝30颗后，爱丽丝比吉姆多40颗；吉姆还剩原来数量的2/3。求两人原来各有多少颗弹珠。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 62,
    "topic": "Fractions",
    "question": "Francis had $3.60 in $0.05 and $0.20 coins. 1/4 of coins were $0.20 coins. Find each coin count.",
    "answer": "Twenty-cent: 16; five-cent: 8",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 25,
    "questionZh": "弗朗西斯有$3.60，由$0.05和$0.20硬币组成。其中1/4的硬币是$0.20硬币。求两种硬币各有多少枚。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 63,
    "topic": "Distance, Speed and Time",
    "question": "Cars P, Q, R were 300 km apart at 8:30 am. Q met P at 11:30 am and R 30 min later; P drove 60 km/h. How far did Q travel between meetings?",
    "answer": "20 km",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 25,
    "questionZh": "上午8:30时，P、Q、R三辆车相距300 km。Q在上午11:30遇到P，30 min后遇到R；P的车速为60 km/h。求Q在两次相遇之间行驶了多远。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 64,
    "topic": "Distance, Speed and Time",
    "question": "Terence and Linda drove A→B at noon. Terence averaged 15 km/h faster; at 4 pm he arrived while Linda covered 224 km. Find A–B distance.",
    "answer": "284 km",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 26,
    "questionZh": "特伦斯和琳达中午从A开往B。特伦斯的平均车速比琳达快15 km/h；下午4:00特伦斯到达B时，琳达已行驶224 km。求A到B的距离。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 65,
    "topic": "Distance, Speed and Time",
    "question": "Aaron drove 80 km/h from 5:30 to 11:30, 1 h 36 min late. If he travelled the initial 1/2 at 100 km/h, find needed later-part speed.",
    "answer": "120 km/h",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 26,
    "questionZh": "亚伦从5:30到11:30以80 km/h行驶，仍晚了1 h 36 min。若他在全程最初的1/2以100 km/h行驶，求后半程所需的速度。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 66,
    "topic": "Distance, Speed and Time",
    "question": "Jasper left A at 8:30 at 90 km/h. Tony left 2 h earlier, 10 km/h slower, and arrived B at 10:30. How far was Jasper from B then?",
    "answer": "140 km",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 26,
    "questionZh": "贾斯珀上午8:30从A出发，车速90 km/h。托尼比他早2 h出发，速度慢10 km/h，并在上午10:30到达B。此时贾斯珀离B还有多远？",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 67,
    "topic": "Distance, Speed and Time",
    "question": "George jogged 9 km/h from 4:15. Caleb began 4:45 and at 5:45 was 2 km ahead. If Caleb had begun at 4:15, how far would he cover?",
    "answer": "23.25 km",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 27,
    "questionZh": "乔治从4:15开始以9 km/h慢跑。凯莱布4:45开始，5:45时他在乔治前面2 km。若凯莱布从4:15开始，他会跑多远？",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 68,
    "topic": "Distance, Speed and Time",
    "question": "A car takes 5 h and bus 9 h for A→B; car speed is 90 km/h. After 3/5 journey, how much faster must bus travel to arrive 1 h 36 min early?",
    "answer": "40 km/h",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 27,
    "questionZh": "一辆汽车和一辆巴士从A到B分别需5 h和9 h；汽车的速度为90 km/h。巴士走完3/5路程后，速度必须提高多少，才能提前1 h 36 min到达？",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 69,
    "topic": "Distance, Speed and Time",
    "question": "Collin was 150 m ahead of Bryan; Aaron was 50 m behind Bryan. At 8:00, Aaron passed Bryan in 2 min and Collin 3 min later. Bryan ran 120 m/min. When did Bryan pass Collin?",
    "answer": "8:10 am",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 27,
    "questionZh": "科林在布莱恩前方150 m；亚伦在布莱恩后方50 m。上午8:00开始，亚伦2 min后超过布莱恩，3 min后又超过科林。布莱恩的跑速为120 m/min。布莱恩何时超过科林？",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 70,
    "topic": "Distance, Speed and Time",
    "question": "Sean drove 90 km/h from 5:30 to 1:30. Mary made the same trip in 6 h. How far was Sean from the destination when they were 150 km apart?",
    "answer": "270 km",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 28,
    "questionZh": "肖恩从5:30到1:30以90 km/h行驶。玛丽用6 h走完相同的路程。当两人相距150 km时，肖恩离目的地还有多远？",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 71,
    "topic": "Distance, Speed and Time",
    "question": "Mark drove 75 km/h from 10:00; Jane left 1 h later at 120 km/h, passed Mark after 2/5 journey, and arrived 4:00. Find requested distance and Mark’s new speed.",
    "answer": "(a) 360 km; (b) 144 km/h",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 28,
    "questionZh": "马克从10:00开始以75 km/h行驶；简1 h后以120 km/h出发，在全程的2/5处超过马克，并于4:00到达。求所要求的距离和马克的新速度。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 72,
    "topic": "Distance, Speed and Time",
    "question": "A 15 cm × 20 cm × 30 cm container was 1/5 full. Taps at 120 and 180 ml/min fill it. How much faster is filling if each tap flows 200 ml/min?",
    "answer": "6 minutes",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 28,
    "questionZh": "一个15 cm × 20 cm × 30 cm的容器装有1/5满的水。两个水龙头的流量分别为120 ml/min和180 ml/min。若每个水龙头的流量均为200 ml/min，注满速度会快多少？",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 73,
    "topic": "Distance, Speed and Time",
    "question": "A car left P at 9:00 at 90 km/h, reached Q 1:00. A lorry left Q at 10:00 and met it after 1/4 distance. Find car distance at meeting and lorry travel time.",
    "answer": "(a) 270 km; (b) 8 h",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 29,
    "questionZh": "一辆汽车上午9:00从P出发，车速90 km/h，下午1:00到达Q。一辆卡车上午10:00从Q出发，在全程的1/4处与汽车相遇。求相遇时汽车行驶的距离和卡车行驶的时间。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 74,
    "topic": "Distance, Speed and Time",
    "question": "Jack drove 80 km/h for 3/5 of a journey, then the remaining 24 km in 12 min. Find total time and second-part speed.",
    "answer": "(a) 34.5 minutes; (b) 120 km/h",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 29,
    "questionZh": "杰克在全程的3/5以80 km/h行驶，剩下的24 km用了12 min。求总用时和第2段的速度。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 75,
    "topic": "Distance, Speed and Time",
    "question": "Tom left A 5:45; Jane left 2 h later at 100 km/h, passed him after 3/5 journey and arrived B 4 h later. Find 3 requested values.",
    "answer": "(a) 400 km; (b) 75 km/h; (c) 7:05 pm",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 29,
    "questionZh": "汤姆5:45从A出发；简2 h后以100 km/h出发，在全程的3/5处超过汤姆，并在4 h后到达B。求3个所要求的数值。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 76,
    "topic": "Distance, Speed and Time",
    "question": "Motorist A left P 9:30 at 80 km/h and arrived Q 3:30. B left 2 h later at 100 km/h. Find B arrival and speed needed to arrive 3:30.",
    "answer": "(a) 4:18 pm; (b) 120 km/h",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 30,
    "questionZh": "驾车人A上午9:30从P出发，车速80 km/h，下午3:30到达Q。B在2 h后以100 km/h从P出发。求B到达时间，以及B若在下午3:30到达所需的速度。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 77,
    "topic": "Distance, Speed and Time",
    "question": "Train A ran X→Z at 160 km/h. Train B took 6 h; both passed Y 2:00 and B reached Z 4:00; Y–Z was 400 km. Find A departure and arrival.",
    "answer": "(a) 9:00 am; (b) 4:30 pm",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 30,
    "questionZh": "火车A以160 km/h从X开往Z。火车B用了6 h；两车都在2:00经过Y，B在4:00到达Z；Y到Z为400 km。求A的出发和到达时间。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 78,
    "topic": "Ratio",
    "question": "A warehouse held 4000 towels; blue:red was 2:1, remaining white. After 1/4 blue and 1/3 white were sold, 2400 remained. Find initial red-plus-white count.",
    "answer": "3200 red and white towels",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 30,
    "questionZh": "一个仓库有4000条毛巾；蓝色与红色毛巾数量之比为2:1，其余为白色。卖出蓝色毛巾的1/4和白色毛巾的1/3后，剩下2400条。求原来红色和白色毛巾的数量总和。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 79,
    "topic": "Ratio",
    "question": "Jar A:B beads were 2:3 and B:C were 2:1. Equal transfers B→A/C make A=B and C=297. Find total beads.",
    "answer": "1053 beads",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 31,
    "questionZh": "罐子A和B中的珠子数量之比为2:3，B和C中的珠子数量之比为2:1。从B向A和C分别转移相同数量的珠子后，A与B数量相等，C中有297颗。求珠子总数。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 80,
    "topic": "Ratio",
    "question": "1/3 of party people were men. After 1/2 men and 8 women left, women exceeded men by 96 before the women left. Find final men:women ratio.",
    "answer": "4:15",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 31,
    "questionZh": "聚会上有1/3是男士。1/2的男士和8名女士离开后，在女士离开前，女士比男士多96人。求最后男士与女士人数之比。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 81,
    "topic": "Ratio",
    "question": "Cindy:Mark marbles were 3:2 of total 80. After Cindy gave away some, she had 1/4 as many as Mark. How many did Cindy give away?",
    "answer": "40 marbles",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 31,
    "questionZh": "辛迪与马克的弹珠数之比为3:2，共80颗。辛迪送出一些弹珠后，她的弹珠数是马克的1/4。辛迪送出了多少颗？",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 82,
    "topic": "Ratio",
    "question": "Country-club men:women was 2:3. 1/4 men and 1/3 women left; remaining people exceeded leavers by 24. Find initial attendance.",
    "answer": "120 people",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 32,
    "questionZh": "乡村俱乐部男士与女士人数之比为2:3。1/4的男士和1/3的女士离开后，留下的人数比离开的人数多24。求起初到场人数。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 83,
    "topic": "Ratio",
    "question": "Mandy:Jack sweets were 5:7; after Mandy gave Jack sweets, ratio became 3:21. Jack initially had 168. How many must Jack return to equalise?",
    "answer": "108 sweets",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 32,
    "questionZh": "曼迪与杰克的糖果数之比为5:7；曼迪给杰克一些糖果后，数量之比变为3:21。杰克起初有168颗糖果。为使两人的糖果数相等，杰克必须还给曼迪多少颗？",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 84,
    "topic": "Ratio",
    "question": "A:B sweets were 7:4 and B:C 3:2. After 36 were removed from A, C was 1/4 of A. Find total sweets left.",
    "answer": "128 sweets",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 32,
    "questionZh": "A与B的糖果数之比为7:4，B与C的糖果数之比为3:2。从A取走36颗糖果后，C的糖果数是A的1/4。求剩下糖果的总数。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 85,
    "topic": "Ratio",
    "question": "1580 people were on a ship; 60% adults. Adults alighted until adults were 20% of remaining. Find adults alighting and final children:adults ratio.",
    "answer": "(a) 790 adults; (b) 4:1",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 33,
    "questionZh": "一艘船上有1580人；其中60%是成年人。部分成年人下船后，成年人占剩余人数的20%。求下船的成年人数，以及最后儿童与成年人的人数之比。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 86,
    "topic": "Ratio",
    "question": "Chocolate cakes cost $4; strawberry cost $3 more than 2 chocolate cakes. Cake counts were 5:3 and Gibbs sold 8 more. Find total sales.",
    "answer": "$212",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 33,
    "questionZh": "巧克力蛋糕每个$4；草莓蛋糕每个比2个巧克力蛋糕贵$3。两种蛋糕的数量之比为5:3，吉布斯卖出的巧克力蛋糕比草莓蛋糕多8个。求总销售额。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 87,
    "topic": "Ratio",
    "question": "Susan sold 1/2 charity tickets; Mark:Jane sold rest 5:3 and Mark exceeded Jane by 18. Tickets cost $1.20. Find total collection.",
    "answer": "$172.80",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 33,
    "questionZh": "苏珊卖出慈善票的1/2；剩余票中马克与简卖出的数量之比为5:3，马克比简多卖18张。每张票$1.20。求总筹款额。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 88,
    "topic": "Ratio",
    "question": "Alvin:Zachary:Philip money was 2:5:3. Zachary spent 20%; his remainder was $196 below Alvin-plus-Philip. How much more did Alvin-plus-Zachary have than Philip?",
    "answer": "$784",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 34,
    "questionZh": "阿尔文、扎卡里和菲利普的钱数之比为2:5:3。扎卡里花掉20%后，剩下的钱比阿尔文和菲利普的钱数总和少$196。阿尔文和扎卡里的钱数总和比菲利普多多少？",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 89,
    "topic": "Percentage",
    "question": "40% of adults left a party; 10% of leavers were men. Men leaving:remaining was 2:5; 105 men were initially present. Find initial women.",
    "answer": "645 women",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 34,
    "questionZh": "聚会上40%的成年人离开；离开者中有10%是男士。离开的男士与留下的男士人数之比为2:5；起初有105名男士。求起初有多少名女士。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 90,
    "topic": "Percentage",
    "question": "Kate took 30% biscuits; Melissa 25%; Jack took final 80; Ann took 20 more than Melissa. What percentage did Ann take?",
    "answer": "29%",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 34,
    "questionZh": "凯特拿走30%的饼干；梅利莎拿走25%；杰克拿走最后80块；安拿走的比梅利莎多20块。安拿走了百分之几的饼干？",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 91,
    "topic": "Percentage",
    "question": "Uncle Sam receives 20% of each $8 cup price plus 5% price for every 10 cups. He collected $86.80. How many cups did he sell?",
    "answer": "53 cups",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 35,
    "questionZh": "山姆叔叔从每杯$8的售价中收取20%，并且每卖10杯另收取售价的5%。他共收了$86.80。他卖出了多少杯？",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 92,
    "topic": "Percentage",
    "question": "20% of a class are boys. 20% boys and 10% girls keep pets; 144 girls do not. How many children keep pets?",
    "answer": "24 children",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 35,
    "questionZh": "一个班级中20%是男生。20%的男生和10%的女生养宠物；144名女生不养宠物。多少名儿童养宠物？",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 93,
    "topic": "Percentage",
    "question": "2/5 marbles were red. Of the remainder, 10% were blue and 10% green. Yellow exceeded red by 32. Find blue-plus-green count.",
    "answer": "48 blue and green marbles",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 35,
    "questionZh": "弹珠中有2/5是红色的。在其余弹珠中，10%是蓝色的，10%是绿色的。黄色弹珠比红色弹珠多32颗。求蓝色和绿色弹珠的总数。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 94,
    "topic": "Percentage",
    "question": "Jane had 40% more marbles than Jeffrey. Jane lost 12 and gave Jeffrey 16, then they matched. Find original counts.",
    "answer": "Jane: 154; Jeffrey: 110",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 36,
    "questionZh": "简的弹珠比杰弗里的多40%。简丢失12颗并给杰弗里16颗后，两人的弹珠数相等。求两人原来各有多少颗弹珠。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 95,
    "topic": "Percentage",
    "question": "Mrs Wood saved 10% salary in month 1 and 50% more in month 2; month-2 saving exceeded month-1 by $496.50. Find 6-month salary.",
    "answer": "$59580",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 36,
    "questionZh": "伍德太太第1个月储蓄工资的10%，第2个月储蓄额比第1个月多50%；第2个月的储蓄额比第1个月多$496.50。求6个月的工资总额。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 96,
    "topic": "Percentage",
    "question": "A square had area 625 cm². Each side increased 40%. Find percentage area increase.",
    "answer": "96%",
    "model": "geometry",
    "hint": "Label the given measures. Draw a model, then calculate the requested value.",
    "sourcePage": 36,
    "questionZh": "一个正方形的面积为625 cm²。每条边增加40%。求面积增加的百分比。",
    "hintZh": "标出已知的度量。画出示意图，再计算所求的值。"
  },
  {
    "id": 97,
    "topic": "Percentage",
    "question": "80% of books were second-hand. 10% new and 60% second-hand were English. Adding 15 English gave English:Chinese 3:2. Find initial English and final total.",
    "answer": "(a) 30 English books; (b) 75 books",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 37,
    "questionZh": "书中80%是二手书。新书中有10%是英文书，二手书中有60%是英文书。增加15本英文书后，英文书与中文书之比为3:2。求起初英文书的数量和最后书的总数。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 98,
    "topic": "Percentage",
    "question": "In January Joyce kept 80% salary, gave 1/4 of it to mother, saved rest; food/clothing was unchanged in February. Mother’s February amount rose $150 and equalled savings. Find requested values.",
    "answer": "(a) 8%; (b) $125",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 37,
    "questionZh": "1月，乔伊斯保留工资的80%，其中1/4给母亲，其余储蓄；2月的食物和衣服支出不变。给母亲的钱在2月增加$150，且等于储蓄额。求题目所要求的数值。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 99,
    "topic": "Percentage",
    "question": "A theatre had 4500 seats: 10% first-class, 30% second-class, rest third-class. Add 200 first and 250 second. Find final first, second, and third percentage.",
    "answer": "(a) 650; (b) 1600; (c) 54 6/11%",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 37,
    "questionZh": "一个剧院有4500个座位：10%是一等座，30%是二等座，其余是三等座。增加200个一等座和250个二等座后，求最后一等、二等和三等座所占的百分比。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 100,
    "topic": "Percentage",
    "question": "Jeremy and Alicia had $360; Jeremy had $24 more. Alicia spent 3 times Jeremy’s spending and retained 1/2 Jeremy’s remainder. Find Jeremy initial and remainder.",
    "answer": "(a) $192; (b) $163.20",
    "model": "money-units",
    "hint": "Label each money amount. Draw equal units, then calculate the requested value.",
    "sourcePage": 38,
    "questionZh": "杰里米和艾丽西亚共有$360；杰里米比艾丽西亚多$24。艾丽西亚的花费是杰里米花费的3倍，并且她剩下的钱是杰里米余款的1/2。求杰里米原有的钱和余款。",
    "hintZh": "标出各项金额。画出等量单位图，再计算所求的值。"
  },
  {
    "id": 101,
    "topic": "Percentage",
    "question": "Crate A had 207 pears, 176 mangoes; B had 293 pears, 274 mangoes. Moving fruit B→A made pears 40% A and 70% B. Find fruit moved.",
    "answer": "167 fruit",
    "model": "fraction-of-remainder",
    "hint": "Underline the given values. Draw equal units, then calculate the requested value.",
    "sourcePage": 38,
    "questionZh": "箱子A中有207个梨和176个芒果；箱子B中有293个梨和274个芒果。将水果从B移到A后，A中的梨占水果总数的40%，B中的梨占水果总数的70%。求转移了多少个水果。",
    "hintZh": "标出已知量。画出等量单位图，再计算所求的值。"
  }
];
